import jsPDF from 'jspdf';
import 'jspdf-autotable';
import type { JournalEntry } from '../services/journalService';

export const generateJournalPDF = (entry: JournalEntry) => {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(20);
  doc.text('Patient Journal Entry', 14, 22);
  doc.setFontSize(12);
  doc.text(`Date: ${new Date(entry.entryDate).toLocaleString()}`, 14, 32);

  // Entry Details
  (doc as any).autoTable({
    startY: 40,
    head: [['Field', 'Details']],
    body: [
      ['Title', entry.title],
      ['Event Type', entry.eventType],
      ['Mood', entry.mood || 'N/A'],
      ['Tags', entry.tags || 'N/A'],
    ],
  });

  // Content
  doc.setFontSize(12);
  doc.text('Detailed Notes:', 14, (doc as any).autoTable.previous.finalY + 15);
  const splitContent = doc.splitTextToSize(entry.content, 180);
  doc.text(splitContent, 14, (doc as any).autoTable.previous.finalY + 25);

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.text(`Page ${i} of ${pageCount}`, 14, 287);
    doc.text('Generated by InPEP Health Hub', 200, 287, { align: 'right' });
  }

  // Save the PDF
  doc.save(`Journal_Entry_${entry.id}.pdf`);
};
