import prisma from '../config/database.js';

const culturalRecipes = [
  // ARABIC CUISINE
  {
    name: 'Heart-Healthy Fattoush Salad',
    description: 'Traditional Lebanese salad with crispy pita, fresh vegetables, and tangy sumac dressing. Light and refreshing!',
    prepTime: 15,
    cookTime: 5,
    servings: 4,
    difficulty: 'EASY',
    category: 'LUNCH',
    cuisine: 'ARABIC',
    dietaryTags: JSON.stringify(['VEGETARIAN', 'HEART_HEALTHY', 'HIGH_FIBER', 'LOW_CALORIE']),
    calories: 185,
    protein: 5,
    carbs: 28,
    fat: 7,
    fiber: 6,
    sugar: 5,
    sodium: 220,
    goodFor: JSON.stringify(['HEART_DISEASE', 'DIABETES', 'HYPERTENSION']),
    ingredients: JSON.stringify([
      { name: 'Whole wheat pita', amount: '2', unit: 'pieces' },
      { name: 'Romaine lettuce', amount: '4', unit: 'cups, chopped' },
      { name: 'Tomatoes', amount: '2', unit: 'large, diced' },
      { name: 'Cucumber', amount: '1', unit: 'large, diced' },
      { name: 'Radishes', amount: '4', unit: 'sliced' },
      { name: 'Fresh mint', amount: '1/4', unit: 'cup' },
      { name: 'Lemon juice', amount: '3', unit: 'tbsp' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
      { name: 'Sumac', amount: '1', unit: 'tsp' },
    ]),
    instructions: JSON.stringify([
      'Toast pita until crispy, then break into pieces',
      'Combine lettuce, tomatoes, cucumber, and radishes',
      'Add fresh mint',
      'Whisk lemon juice, olive oil, and sumac',
      'Toss salad with dressing',
      'Top with crispy pita pieces',
      'Serve immediately',
    ]),
    tips: 'Add pita just before serving to keep it crispy',
    rating: 4.8,
    reviewCount: 167,
  },
  {
    name: 'Mujadara (Lentils & Rice)',
    description: 'Classic Arabic comfort food with lentils, rice, and caramelized onions. Protein-rich and heart-healthy!',
    prepTime: 10,
    cookTime: 40,
    servings: 6,
    difficulty: 'MEDIUM',
    category: 'DINNER',
    cuisine: 'ARABIC',
    dietaryTags: JSON.stringify(['VEGAN', 'HIGH_PROTEIN', 'HIGH_FIBER', 'HEART_HEALTHY']),
    calories: 310,
    protein: 12,
    carbs: 54,
    fat: 6,
    fiber: 10,
    sugar: 4,
    sodium: 180,
    goodFor: JSON.stringify(['HEART_DISEASE', 'DIABETES', 'HYPERTENSION']),
    ingredients: JSON.stringify([
      { name: 'Brown lentils', amount: '1', unit: 'cup' },
      { name: 'Brown rice', amount: '1', unit: 'cup' },
      { name: 'Onions', amount: '3', unit: 'large, sliced' },
      { name: 'Olive oil', amount: '2', unit: 'tbsp' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'Vegetable broth', amount: '4', unit: 'cups, low-sodium' },
    ]),
    instructions: JSON.stringify([
      'Cook lentils in broth for 20 minutes',
      'Add rice and continue cooking for 20 minutes',
      'Meanwhile, caramelize onions in olive oil',
      'Season lentils and rice with cumin',
      'Serve topped with caramelized onions',
    ]),
    tips: 'Serve with a side of yogurt for added protein',
    rating: 4.9,
    reviewCount: 234,
  },

  // INDIAN CUISINE
  {
    name: 'Diabetic-Friendly Daal (Lentil Curry)',
    description: 'Aromatic Indian lentil curry with turmeric and spices. Anti-inflammatory and blood sugar friendly!',
    prepTime: 10,
    cookTime: 30,
    servings: 6,
    difficulty: 'EASY',
    category: 'DINNER',
    cuisine: 'INDIAN',
    dietaryTags: JSON.stringify(['VEGAN', 'GLUTEN_FREE', 'HIGH_PROTEIN', 'ANTI_INFLAMMATORY']),
    calories: 220,
    protein: 14,
    carbs: 38,
    fat: 3,
    fiber: 12,
    sugar: 3,
    sodium: 200,
    goodFor: JSON.stringify(['DIABETES', 'HEART_DISEASE', 'HYPERTENSION']),
    ingredients: JSON.stringify([
      { name: 'Red lentils', amount: '1.5', unit: 'cups' },
      { name: 'Onion', amount: '1', unit: 'large, diced' },
      { name: 'Tomatoes', amount: '2', unit: 'medium, diced' },
      { name: 'Garlic', amount: '4', unit: 'cloves, minced' },
      { name: 'Ginger', amount: '1', unit: 'tbsp, grated' },
      { name: 'Turmeric', amount: '1', unit: 'tsp' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'Garam masala', amount: '1', unit: 'tsp' },
      { name: 'Vegetable broth', amount: '4', unit: 'cups, low-sodium' },
      { name: 'Fresh cilantro', amount: '1/4', unit: 'cup' },
    ]),
    instructions: JSON.stringify([
      'Rinse lentils thoroughly',
      'Sauté onion, garlic, and ginger',
      'Add spices and cook for 1 minute',
      'Add lentils, tomatoes, and broth',
      'Simmer for 25-30 minutes until creamy',
      'Garnish with fresh cilantro',
      'Serve with brown rice or whole wheat roti',
    ]),
    tips: 'Turmeric is a powerful anti-inflammatory for heart health',
    rating: 4.9,
    reviewCount: 312,
  },
  {
    name: 'Masala Chai (Spiced Tea)',
    description: 'Traditional Indian spiced tea with cardamom, ginger, and cinnamon. Warming and antioxidant-rich!',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: 'EASY',
    category: 'SNACK',
    cuisine: 'INDIAN',
    dietaryTags: JSON.stringify(['VEGETARIAN', 'LOW_CALORIE', 'ANTI_INFLAMMATORY']),
    calories: 80,
    protein: 4,
    carbs: 12,
    fat: 2,
    fiber: 0,
    sugar: 8,
    sodium: 60,
    goodFor: JSON.stringify(['HEART_DISEASE', 'DIABETES']),
    ingredients: JSON.stringify([
      { name: 'Water', amount: '1.5', unit: 'cups' },
      { name: 'Low-fat milk', amount: '1', unit: 'cup' },
      { name: 'Black tea', amount: '2', unit: 'tsp' },
      { name: 'Cardamom pods', amount: '3', unit: 'crushed' },
      { name: 'Fresh ginger', amount: '1', unit: 'inch, sliced' },
      { name: 'Cinnamon stick', amount: '1', unit: 'small' },
      { name: 'Honey', amount: '1', unit: 'tsp (optional)' },
    ]),
    instructions: JSON.stringify([
      'Boil water with spices for 5 minutes',
      'Add tea and simmer for 2 minutes',
      'Add milk and bring to a boil',
      'Strain into cups',
      'Add honey if desired',
      'Serve hot',
    ]),
    tips: 'Ginger aids digestion and reduces inflammation',
    rating: 4.7,
    reviewCount: 189,
  },

  // BRAZILIAN CUISINE
  {
    name: 'Feijoada Light (Brazilian Black Bean Stew)',
    description: 'Lighter version of Brazil\'s national dish. Rich in protein and fiber, perfect for heart health!',
    prepTime: 15,
    cookTime: 45,
    servings: 8,
    difficulty: 'MEDIUM',
    category: 'DINNER',
    cuisine: 'BRAZILIAN',
    dietaryTags: JSON.stringify(['GLUTEN_FREE', 'HIGH_PROTEIN', 'HIGH_FIBER']),
    calories: 295,
    protein: 18,
    carbs: 42,
    fat: 6,
    fiber: 14,
    sugar: 3,
    sodium: 280,
    goodFor: JSON.stringify(['HEART_DISEASE', 'DIABETES']),
    ingredients: JSON.stringify([
      { name: 'Black beans', amount: '2', unit: 'cans (15oz each)' },
      { name: 'Lean turkey sausage', amount: '8', unit: 'oz, sliced' },
      { name: 'Onion', amount: '1', unit: 'large, diced' },
      { name: 'Garlic', amount: '4', unit: 'cloves, minced' },
      { name: 'Bay leaves', amount: '2', unit: 'leaves' },
      { name: 'Orange', amount: '1', unit: 'juiced' },
      { name: 'Tomatoes', amount: '2', unit: 'diced' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'Smoked paprika', amount: '1', unit: 'tsp' },
    ]),
    instructions: JSON.stringify([
      'Sauté turkey sausage until browned',
      'Add onion and garlic, cook until soft',
      'Add black beans with liquid',
      'Add tomatoes, orange juice, and spices',
      'Simmer for 30 minutes',
      'Remove bay leaves',
      'Serve with brown rice and orange slices',
    ]),
    tips: 'Traditional with pork, but turkey makes it heart-healthy',
    rating: 4.8,
    reviewCount: 156,
  },

  // ITALIAN CUISINE
  {
    name: 'Pasta Primavera (Heart-Healthy)',
    description: 'Colorful Italian pasta with fresh vegetables and light olive oil. Mediterranean diet at its best!',
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: 'EASY',
    category: 'DINNER',
    cuisine: 'ITALIAN',
    dietaryTags: JSON.stringify(['VEGETARIAN', 'HEART_HEALTHY', 'MEDITERRANEAN']),
    calories: 340,
    protein: 12,
    carbs: 52,
    fat: 10,
    fiber: 8,
    sugar: 6,
    sodium: 180,
    goodFor: JSON.stringify(['HEART_DISEASE', 'HYPERTENSION']),
    ingredients: JSON.stringify([
      { name: 'Whole wheat pasta', amount: '12', unit: 'oz' },
      { name: 'Zucchini', amount: '2', unit: 'medium, sliced' },
      { name: 'Bell peppers', amount: '2', unit: 'sliced' },
      { name: 'Cherry tomatoes', amount: '2', unit: 'cups, halved' },
      { name: 'Garlic', amount: '4', unit: 'cloves, minced' },
      { name: 'Olive oil', amount: '3', unit: 'tbsp' },
      { name: 'Fresh basil', amount: '1/2', unit: 'cup' },
      { name: 'Parmesan', amount: '1/4', unit: 'cup, grated' },
    ]),
    instructions: JSON.stringify([
      'Cook pasta according to package directions',
      'Sauté garlic in olive oil',
      'Add zucchini and peppers, cook 5 minutes',
      'Add cherry tomatoes, cook 3 minutes',
      'Toss with cooked pasta',
      'Add fresh basil',
      'Top with Parmesan',
    ]),
    tips: 'Use whole wheat pasta for extra fiber and better blood sugar control',
    rating: 4.7,
    reviewCount: 203,
  },
  {
    name: 'Caprese Salad',
    description: 'Classic Italian salad with tomatoes, mozzarella, and basil. Simple, fresh, and heart-healthy!',
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: 'EASY',
    category: 'LUNCH',
    cuisine: 'ITALIAN',
    dietaryTags: JSON.stringify(['VEGETARIAN', 'GLUTEN_FREE', 'NO_COOK', 'MEDITERRANEAN']),
    calories: 220,
    protein: 12,
    carbs: 8,
    fat: 16,
    fiber: 2,
    sugar: 5,
    sodium: 320,
    goodFor: JSON.stringify(['HEART_DISEASE']),
    ingredients: JSON.stringify([
      { name: 'Fresh mozzarella', amount: '8', unit: 'oz, sliced' },
      { name: 'Tomatoes', amount: '3', unit: 'large, sliced' },
      { name: 'Fresh basil', amount: '1/2', unit: 'cup, leaves' },
      { name: 'Balsamic vinegar', amount: '2', unit: 'tbsp' },
      { name: 'Olive oil', amount: '1', unit: 'tbsp' },
      { name: 'Salt and pepper', amount: 'to taste', unit: '' },
    ]),
    instructions: JSON.stringify([
      'Arrange tomato and mozzarella slices alternating',
      'Tuck basil leaves between slices',
      'Drizzle with balsamic vinegar and olive oil',
      'Season with salt and pepper',
      'Let sit for 5 minutes before serving',
    ]),
    tips: 'Use fresh, ripe tomatoes for best flavor',
    rating: 4.6,
    reviewCount: 178,
  },

  // TURKISH CUISINE
  {
    name: 'Turkish Lentil Soup (Mercimek Çorbası)',
    description: 'Creamy red lentil soup with cumin and lemon. Turkish comfort food that\'s incredibly healthy!',
    prepTime: 10,
    cookTime: 30,
    servings: 6,
    difficulty: 'EASY',
    category: 'LUNCH',
    cuisine: 'TURKISH',
    dietaryTags: JSON.stringify(['VEGAN', 'GLUTEN_FREE', 'HIGH_PROTEIN', 'HIGH_FIBER']),
    calories: 195,
    protein: 11,
    carbs: 34,
    fat: 3,
    fiber: 10,
    sugar: 4,
    sodium: 190,
    goodFor: JSON.stringify(['HEART_DISEASE', 'DIABETES', 'HYPERTENSION']),
    ingredients: JSON.stringify([
      { name: 'Red lentils', amount: '1.5', unit: 'cups' },
      { name: 'Onion', amount: '1', unit: 'large, diced' },
      { name: 'Carrots', amount: '2', unit: 'medium, diced' },
      { name: 'Tomato paste', amount: '1', unit: 'tbsp' },
      { name: 'Vegetable broth', amount: '6', unit: 'cups, low-sodium' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'Paprika', amount: '1/2', unit: 'tsp' },
      { name: 'Lemon', amount: '1', unit: 'juiced' },
      { name: 'Fresh mint', amount: '2', unit: 'tbsp' },
    ]),
    instructions: JSON.stringify([
      'Sauté onion and carrots until soft',
      'Add tomato paste and spices',
      'Add lentils and broth',
      'Simmer for 25 minutes until lentils are soft',
      'Blend until smooth (optional)',
      'Add lemon juice',
      'Garnish with fresh mint',
    ]),
    tips: 'Serve with a squeeze of lemon for authentic Turkish flavor',
    rating: 4.9,
    reviewCount: 267,
  },
  {
    name: 'Turkish Breakfast Bowl',
    description: 'Traditional Turkish breakfast with olives, tomatoes, cucumber, and cheese. Mediterranean goodness!',
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    difficulty: 'EASY',
    category: 'BREAKFAST',
    cuisine: 'TURKISH',
    dietaryTags: JSON.stringify(['VEGETARIAN', 'NO_COOK', 'MEDITERRANEAN', 'HIGH_PROTEIN']),
    calories: 285,
    protein: 14,
    carbs: 32,
    fat: 12,
    fiber: 6,
    sugar: 8,
    sodium: 420,
    goodFor: JSON.stringify(['HEART_DISEASE']),
    ingredients: JSON.stringify([
      { name: 'Whole grain bread', amount: '2', unit: 'slices' },
      { name: 'Feta cheese', amount: '2', unit: 'oz' },
      { name: 'Tomatoes', amount: '1', unit: 'large, sliced' },
      { name: 'Cucumber', amount: '1/2', unit: 'sliced' },
      { name: 'Kalamata olives', amount: '6', unit: 'pitted' },
      { name: 'Hard-boiled egg', amount: '1', unit: 'sliced' },
      { name: 'Fresh mint', amount: '2', unit: 'tbsp' },
      { name: 'Olive oil', amount: '1', unit: 'tsp' },
    ]),
    instructions: JSON.stringify([
      'Arrange all ingredients on a plate',
      'Drizzle with olive oil',
      'Sprinkle with fresh mint',
      'Serve with whole grain bread',
    ]),
    tips: 'Rinse feta to reduce sodium content',
    rating: 4.6,
    reviewCount: 145,
  },

  // MEXICAN/LATIN CUISINE
  {
    name: 'Black Bean & Sweet Potato Tacos',
    description: 'Healthy Mexican-inspired tacos with roasted sweet potato and black beans. Fiber-rich and delicious!',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'EASY',
    category: 'DINNER',
    cuisine: 'MEXICAN',
    dietaryTags: JSON.stringify(['VEGAN', 'HIGH_FIBER', 'HIGH_PROTEIN']),
    calories: 320,
    protein: 12,
    carbs: 58,
    fat: 6,
    fiber: 14,
    sugar: 8,
    sodium: 280,
    goodFor: JSON.stringify(['DIABETES', 'HEART_DISEASE']),
    ingredients: JSON.stringify([
      { name: 'Sweet potatoes', amount: '2', unit: 'large, cubed' },
      { name: 'Black beans', amount: '1', unit: 'can (15oz)' },
      { name: 'Corn tortillas', amount: '8', unit: 'small' },
      { name: 'Avocado', amount: '1', unit: 'sliced' },
      { name: 'Lime', amount: '1', unit: 'juiced' },
      { name: 'Cumin', amount: '1', unit: 'tsp' },
      { name: 'Chili powder', amount: '1/2', unit: 'tsp' },
      { name: 'Fresh cilantro', amount: '1/4', unit: 'cup' },
    ]),
    instructions: JSON.stringify([
      'Roast sweet potato cubes with spices at 400°F for 25 minutes',
      'Warm black beans',
      'Warm tortillas',
      'Fill tortillas with sweet potato and beans',
      'Top with avocado, cilantro, and lime juice',
    ]),
    tips: 'Use corn tortillas for authentic flavor and gluten-free option',
    rating: 4.8,
    reviewCount: 198,
  },

  // ASIAN CUISINE
  {
    name: 'Miso Soup with Tofu',
    description: 'Traditional Japanese soup with fermented miso, tofu, and seaweed. Probiotic-rich and low-calorie!',
    prepTime: 5,
    cookTime: 10,
    servings: 4,
    difficulty: 'EASY',
    category: 'SNACK',
    cuisine: 'ASIAN',
    dietaryTags: JSON.stringify(['VEGAN', 'GLUTEN_FREE', 'LOW_CALORIE', 'PROBIOTIC']),
    calories: 85,
    protein: 6,
    carbs: 8,
    fat: 4,
    fiber: 2,
    sugar: 2,
    sodium: 580,
    goodFor: JSON.stringify(['HEART_DISEASE', 'DIABETES']),
    ingredients: JSON.stringify([
      { name: 'Water', amount: '4', unit: 'cups' },
      { name: 'Miso paste', amount: '3', unit: 'tbsp, low-sodium' },
      { name: 'Firm tofu', amount: '8', unit: 'oz, cubed' },
      { name: 'Wakame seaweed', amount: '2', unit: 'tbsp, dried' },
      { name: 'Green onions', amount: '2', unit: 'sliced' },
    ]),
    instructions: JSON.stringify([
      'Bring water to a simmer',
      'Add tofu and seaweed',
      'Simmer for 5 minutes',
      'Remove from heat',
      'Dissolve miso paste in a small amount of broth',
      'Stir miso mixture into soup',
      'Garnish with green onions',
      'Serve immediately',
    ]),
    tips: 'Never boil miso - it kills the beneficial probiotics',
    rating: 4.5,
    reviewCount: 134,
  },
];

async function seedCulturalRecipes() {
  console.log('🌍 Seeding cultural recipes...');

  try {
    for (const recipe of culturalRecipes) {
      await prisma.recipe.create({ data: recipe });
    }
    
    console.log(`✅ Created ${culturalRecipes.length} cultural recipes`);
    console.log('\n📊 Cuisines added:');
    console.log('   - Arabic: 2 recipes (Fattoush, Mujadara)');
    console.log('   - Indian: 2 recipes (Daal, Masala Chai)');
    console.log('   - Brazilian: 1 recipe (Feijoada)');
    console.log('   - Italian: 2 recipes (Pasta Primavera, Caprese)');
    console.log('   - Mexican: 1 recipe (Black Bean Tacos)');
    console.log('   - Asian: 1 recipe (Miso Soup)');
    console.log('\n🎉 Cultural recipe seeding complete!');
    console.log(`📖 Total recipes in database: ${await prisma.recipe.count()}`);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

seedCulturalRecipes()
  .catch((error) => {
    console.error('❌ Script failed:', error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
